# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
    ]
